#!/usr/bin/env bash
set -e

# Usage:
#   script/test <test_file>
#   script/test

if [ -d test/dest ]
  then rm -r test/dest
fi

if [[ $# -lt 1 ]]
then
  set -x
  time ruby -S bundle exec \
    rake test
else
  set -x
  time ruby -S bundle exec ruby -I test \
    "$@"
fi
